### ISSUE TITLE
When popping examples off the stack an exception is thrown

### ISSUE THREAD

**Issue by drewdeponte** [uptech/flutter_forge#8]
This only seems to have started happening since I made all of the components separate libraries. It is reproducible by simply running the example app, clicking any of the buttons to go to any of the examples, then simply click the back button and see the following exception.

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by
calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack:
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4241:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4255:6)
#2      Element.getElementForInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:4286:12)
#3      ProviderScope.containerOf (package:flutter_riverpod/src/framework.dart:99:12)
#4      ConsumerStatefulElement.read (package:flutter_riverpod/src/consumer.dart:552:26)
#5      Store.viewStore (package:flutter_forge/src/store.dart:23:16)
#6      _ComponentState.dispose (package:flutter_forge/src/component_widget.dart:46:26)
#7      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:5105:11)
#8      ConsumerStatefulElement.unmount (package:flutter_riverpod/src/consumer.dart:529:11)
#9      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1917:13)
#10     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#11     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#12     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#13     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#14     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#15     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#16     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#17     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#18     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#19     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#20     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#21     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#22     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#23     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#26     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6398:16)
#27     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#28     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#29     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#30     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#31     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#32     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#38     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#39     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#40     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#41     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#42     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#43     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#44     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#45     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#46     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#47     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#48     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#49     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#50     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#51     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#52     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#53     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#54     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#55     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#56     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#57     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#58     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#59     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#60     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#61     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#62     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#63     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#64     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#65     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#66     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#67     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#68     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#69     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#70     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#71     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#72     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#73     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#74     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#75     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#76     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#77     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#78     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#79     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#80     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#81     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#82     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#83     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#84     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#85     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#86     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#87     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#88     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#89     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#90     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#91     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#92     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#93     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#94     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#95     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#96     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#97     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#98     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#99     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#100    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#101    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#102    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#103    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#104    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#105    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#106    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#107    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#108    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#109    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#110    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#111    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#112    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#113    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#114    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#115    ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#116    _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1926:25)
#117    BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2523:15)
#118    BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2947:7)
#119    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:885:19)
#120    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#121    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#122    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#123    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#124    _invoke (dart:ui/hooks.dart:148:13)
#125    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#126    _drawFrame (dart:ui/hooks.dart:115:31)
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: Looking up a deactivated widget's ancestor is unsafe.
```

**Comment by drewdeponte** [comment]
This has been resolved and integrated via aae3ccd.
